var data = [
  {
    "lastName": "Garg",
    "empProfilePicLocation": "",
    "extension": "",
    "mobile": "8295540701",
    "buName": "Imaginea",
    "employeeCode": "13642",
    "yammerProfileUrl": "",
    "workLocation": "Hyderabad",
    "firstName": "Aakriti",
    "bloodGroup": "AB+",
    "cubical": "LGF044",
    "roleName": "Development Engineer",
    "email": "aakriti.garg@imaginea.com"
  },
  {
    "lastName": "Soundararajan",
    "empProfilePicLocation": "",
    "extension": "23577",
    "mobile": "+919884332396",
    "buName": "Pramati",
    "employeeCode": "10868",
    "yammerProfileUrl": "",
    "workLocation": "Chennai",
    "firstName": "Aarthy",
    "bloodGroup": "O-",
    "cubical": "HR Room-WS01",
    "roleName": "Associate Manager",
    "email": "aarthy.s@pramati.com"
  },
  {
    "lastName": "Diwan",
    "empProfilePicLocation": "",
    "extension": "14182",
    "mobile": "9985478909",
    "buName": "Pramati",
    "employeeCode": "12557",
    "yammerProfileUrl": "",
    "workLocation": "Hyderabad",
    "firstName": "Aayush",
    "bloodGroup": "O-",
    "cubical": "2F012",
    "roleName": "Manager",
    "email": "aayush.diwan@pramati.com"
  },
  {
    "lastName": "Vijayamohan",
    "empProfilePicLocation": "",
    "extension": "",
    "mobile": "8547871997",
    "buName": "Imaginea",
    "employeeCode": "13319",
    "yammerProfileUrl": "",
    "workLocation": "Chennai",
    "firstName": "Abba Vishnu",
    "bloodGroup": "O+",
    "cubical": "A324",
    "roleName": "Visual Designer",
    "email": "abba.vishnu@imaginea.com"
  },
  {
    "lastName": "Pajapalla",
    "empProfilePicLocation": "",
    "extension": "",
    "mobile": "9901726111",
    "buName": "GTC",
    "employeeCode": "13526",
    "yammerProfileUrl": "",
    "workLocation": "Bengaluru",
    "firstName": "Abdul",
    "bloodGroup": "B+",
    "cubical": "",
    "roleName": "Development Engineer",
    "email": "abdul.pajapalla@imaginea.com"
  },
  {
    "lastName": "A",
    "empProfilePicLocation": "",
    "extension": "",
    "mobile": "9965471240",
    "buName": "Imaginea",
    "employeeCode": "11463",
    "yammerProfileUrl": "",
    "workLocation": "Chennai",
    "firstName": "Abdul Rafiu",
    "bloodGroup": "O+",
    "cubical": "B305",
    "roleName": "Principal Engineer",
    "email": "abdul.rafiu@imaginea.com"
  },
  {
    "lastName": "Aavula",
    "empProfilePicLocation": "",
    "extension": "14226",
    "mobile": "9849729133",
    "buName": "Pramati",
    "employeeCode": "12455",
    "yammerProfileUrl": "",
    "workLocation": "Hyderabad",
    "firstName": "Abhijeet",
    "bloodGroup": "A+",
    "cubical": "2F021",
    "roleName": "Manager",
    "email": "abhijeet.aavula@pramati.com"
  },
  {
    "lastName": "Sinha",
    "empProfilePicLocation": "",
    "extension": "",
    "mobile": "9952924609",
    "buName": "Imaginea",
    "employeeCode": "13137",
    "yammerProfileUrl": "",
    "workLocation": "Hyderabad",
    "firstName": "Abhijit",
    "bloodGroup": "B+",
    "cubical": "4F134",
    "roleName": "Senior Development Engineer",
    "email": "abhijit.sinha@imaginea.com"
  },
  {
    "lastName": "Sridhar",
    "empProfilePicLocation": "",
    "extension": "",
    "mobile": "+919538607156",
    "buName": "GTC",
    "employeeCode": "12921",
    "yammerProfileUrl": "",
    "workLocation": "Bengaluru",
    "firstName": "Abhijith",
    "bloodGroup": "O+",
    "cubical": "",
    "roleName": "Quality Lead",
    "email": "abhijith.sridhar@imaginea.com"
  },
  {
    "lastName": "Karlapudi",
    "empProfilePicLocation": "",
    "extension": "",
    "mobile": "+919849237397",
    "buName": "Imaginea",
    "employeeCode": "11410",
    "yammerProfileUrl": "",
    "workLocation": "Hyderabad",
    "firstName": "Abhilash yadav",
    "bloodGroup": "O+",
    "cubical": "2F096",
    "roleName": "Principal Engineer, QA",
    "email": "abhilash.karlapudi@imaginea.com"
  }
]
